-include ../../common.mk

#sets the hex file to be built as part of a full build
all: balancepihat.hex

#adds appropriate libraries to the compiled firmware
balancepihat.hex: system.a util.a output.a
